version: '3.8'

services:
  http-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/static
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/hello"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 